# Debugging Exercise: Matrix Multiplication

## The Importance of Debugging Skills
Almost everybody who uses a computer has encountered a bug. It might have been a rendering issue on a website, unexpected behavior in a video game, or a bug severe enough to crash an entire application or operating system. The ubiquity of software bugs indicates--what many have found out the hard way--that programming is hard to get right.

As some may have discovered already, every programmer will get an ample amount of opportunities to debug software. Many beginning programmers are intimidated by error messages. However, the ability to push through errors and fix them is what makes one a more competent and confident programmer.

## Topics Covered
### `print()` debugging
`print()` debugging is the act of trying to determine the source of a bug in a program by printing out the values of some variables and outputs. It is a primitive form of debugging that some programmers frown upon, but it is a useful tool that is also easy to learn. Once you understand `print()` debugging, you can move on to other more sophisticated methods such as
 1. Logging
 2. Using Python's debugger (PDB)
 
### Reading error messages
Another hint of what went wrong is precisely what Python tells you what went wrong. In addition to providing concise error messages which describe the most immediate cause of a program not working, Python also provides **tracebacks**. This is useful in the case of functions which call other functions which then call other functions and so on. By providing a history of these function calls, **tracebacks** help us diagnose software errors which might not be caused by the most immediate suspect.

## This Exercise: Matrix Multiplication
For this exercise, I decided to choose something that was relatively challenging to implement (and therefore debug). As a result, this exercise involves debugging a function that is intended to perform matrix multiplication. Now, there are actually several methods of multiplying matrices together. The algorithm implemented here is based on the one that most have learned in a basic linear algebra course. While not the fastest algorithm, it is the most widely known.

In general, there is actually no point in implementing matrix multiplication in Python. The `numpy` package has its own implementation of matrices and along with a fast matrix multiplication algorithm. However, because matrix multiplication is relatively challenging and requries many things to go right at the same time, it is a good opportunity to practice debugging. Here, we can use the `numpy` package to check our work.

### The Algorithm
As was taught in school, to multiply two matrices together, we need to make sure they are of compatible dimensions. For a matrix with $m$ rows and $n$ columns, we can multiply it with another matrix with any number $p$ of columns but only $n$ rows. The resultant matrix then has $n$ rows and $p$ columns.

To explicate this further, suppose the first matrix looks like:

$\begin{bmatrix}
a_{11} & a_{12} & ... & a_{1m}
\end{bmatrix}
$



If you forgot how to matrix multiply, look up a few simple examples so you can follow along. Then, for any entry located at say, row $i$ and column $j$, its value is equal to the sum of each 

In [87]:
import numpy as np

In [2]:
matrix_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix_1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [3]:
matrix_1[2]

[7, 8, 9]

In [50]:
def matrix_multiply(a, b):
    def entry_sum(row, col):
        # Calculate the value of an individual entry in the resultant matrix,
        # given the row and column indices of the entry
        this_sum = 0
        
        i = 0
        for num in a[row]:
            i += 1
            this_sum += num * b[i][col]
            
        return this_sum
        
    # For every row in the original matrix, add a row to the new matrix
    result = [list() for row in a]
    
    # Populate matrix with results
    row = 0
    for row in result:
        # Populate columns
        col = 0
        for col in a[1]:
            row.append(entry_sum(row, col))
            col += 1
            
        row += 1
    
    return(result)
        
matrix_multiply(matrix_1, matrix_1)

TypeError: list indices must be integers or slices, not list

## Step 1: Now what?
This function is a rather complex chain of functions. Let's make sure entry_sum() works.

In [44]:
def entry_sum(a, b, row, col):
    # Calculate the value of an individual entry in the resultant matrix,
    # given the row and column indices of the entry
    this_sum = 0

    i = 0
    for num in a[i]:
        i += 1
        this_sum += num * b[i][col]
        
    return this_sum

In [39]:
matrix_2 = [[1, 2], [3, 4]]
matrix_3 = [[1, 3], [1, 3]]
matrix_2

[[1, 2], [3, 4]]

In [40]:
matrix_3

[[1, 3], [1, 3]]

In [42]:
import numpy as np

np.matrix(matrix_2) * np.matrix(matrix_3)

matrix([[ 3,  9],
        [ 7, 21]])

In [43]:
entry_sum(matrix_2, matrix_3, row=0, col=0)

num: 1
a[i]: [1, 2]
i: 0
this_sum: 1
num: 2
a[i]: [3, 4]
i: 1
this_sum: 7


In [63]:
def entry_sum(a, b, row, col):
    # Calculate the value of an individual entry in the resultant matrix,
    # given the row and column indices of the entry
    this_sum = 0

    i = 0
    for num in a[row]:
        this_sum += num * b[i][col]
        i += 1
        
    return this_sum

In [64]:
entry_sum(matrix_2, matrix_3, row=0, col=0)

3

In [65]:
entry_sum(matrix_2, matrix_3, row=0, col=1)

9

In [61]:
entry_sum(matrix_2, matrix_3, row=1, col=0)

7

In [62]:
entry_sum(matrix_2, matrix_3, row=1, col=1)

21

In [69]:
def matrix_multiply(a, b):
    def entry_sum(row, col):
        # Calculate the value of an individual entry in the resultant matrix,
        # given the row and column indices of the entry
        this_sum = 0

        i = 0
        for num in a[row]:
            this_sum += num * b[i][col]
            i += 1

        return this_sum
        
    # For every row in the original matrix, add a row to the new matrix
    result = [list() for row in a]
    
    # Populate matrix with results
    r = 0
    for row in result:
        # Populate columns
        c = 0
        for col in a[1]:
            row.append(entry_sum(r, c))
            c += 1
            
        r += 1
    
    return(result)
        
matrix_multiply(matrix_2, matrix_3)

[[3, 9], [7, 21]]

## Unit Testing


In [85]:
# %load tests/matrix_multiplication_tests.py
# Import the unittest module to create unit tests
import unittest

# Import our function to be tested
#from matrix_multiplication import matrix_multiply

class MatrixMultiplicationTest(unittest.TestCase):

    '''
     * We can name our methods anything we want as long as they begin with 'test'
     * Each method corresponds with one test
    '''
    def test_3x3_identity(self):
        matrix_1 = [[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]]
        matrix_2 = [[1, 0, 0],
                    [0, 1, 0],
                    [0, 0, 1]]
                  
        expected_answer = matrix_1
        output = matrix_multiply(matrix_1, matrix_2)
        
        self.assertEqual(output, expected_answer)

# Put this final clause to make your tests run when this script is executed!
#if __name__ == '__main__':
unittest.main()

E
ERROR: C:\Users\vince\AppData\Roaming\jupyter\runtime\kernel-37c6f43c-6480-4382-a78a-952b2d69538f (unittest.loader._FailedTest)
----------------------------------------------------------------------
AttributeError: module '__main__' has no attribute 'C:\Users\vince\AppData\Roaming\jupyter\runtime\kernel-37c6f43c-6480-4382-a78a-952b2d69538f'

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (errors=1)


SystemExit: True

c:\users\vince\appdata\local\programs\python\python36-32\lib\site-packages\IPython\core\interactiveshell.py:2889: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [86]:
matrix_1 = [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
            [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
            [31, 59, 68, 123, 345, 123, 145, 1000, 1023, 435],
            [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
            [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
            [31, 59, 68, 123, 345, 123, 145, 1000, 1023, 435],
            [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
            [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
            [31, 59, 68, 123, 345, 123, 145, 1000, 1023, 435],
            [31, 59, 68, 123, 345, 123, 145, 1000, 1023, 435]]
matrix_2 = [[1, 123, 23],
            [2, 2, 2],
            [2, 2, 2],
            [123, 123, 432],
            [4394, 432, 23],
            [1, 123, 23],
            [2, 2, 2],
            [2, 2, 2],
            [123, 123, 432],
            [4394, 432, 23]]

In [88]:
np.matrix(matrix_1) * np.matrix(matrix_2)

matrix([[  67556,    8980,    6162],
        [ 971956,  145380,  102562],
        [3570976,  499404,  519098],
        [  67556,    8980,    6162],
        [ 971956,  145380,  102562],
        [3570976,  499404,  519098],
        [  67556,    8980,    6162],
        [ 971956,  145380,  102562],
        [3570976,  499404,  519098],
        [3570976,  499404,  519098]])

## Error: 10x10 * 10x3
It appears our function does not work when multiplying matrices of unequal dimensions.
<pre><code>ERROR: test_10x10_10x3 (__main__.MatrixMultiplicationTest)
<span>----------------------------------------------------------------------</span>
Traceback (most recent call last):
  File "C:\Users\vince\Dropbox\My Projects\Python-Notes\Untitled Folder\tests\matrix_multiplication_tests.py", line 74, in test_10x10_10x3
    output = matrix_multiply(matrix_1, matrix_2)
  File "C:\Users\vince\Dropbox\My Projects\Python-Notes\Untitled Folder\tests\matrix_multiplication.py", line 23, in matrix_multiply
    row.append(entry_sum(r, c))
  File "C:\Users\vince\Dropbox\My Projects\Python-Notes\Untitled Folder\tests\matrix_multiplication.py", line 9, in entry_sum
    this_sum += num * b[i][col]
IndexError: list index out of range</code></pre>

In [103]:
matrix_1 = [[1, 15, 1],
            [13, 1, 8],
            [1, 1, 90]]

matrix_2 = [[1, 9],
            [5, 17],
            [2, 31]]

### Correct Output

In [104]:
np.matrix(matrix_1) * np.matrix(matrix_2)

matrix([[  78,  295],
        [  34,  382],
        [ 186, 2816]])

### Actual Output

In [91]:
matrix_multiply(matrix_1, matrix_2)

IndexError: list index out of range

## Fixing
Since the traceback directly pointed out our `entry_sum()` function as being the main location where the error occurred, we will pull it out again and manually verify that it works for each entry.

In [92]:
def entry_sum(a, b, row, col):
    # Calculate the value of an individual entry in the resultant matrix,
    # given the row and column indices of the entry
    this_sum = 0

    i = 0
    for num in a[row]:
        this_sum += num * b[i][col]
        i += 1
        
    return this_sum

In [110]:
entry_sum(matrix_1, matrix_2, row=0, col=0)


78

In [112]:
entry_sum(matrix_1, matrix_2, row=0, col=1)

295

In [113]:
entry_sum(matrix_1, matrix_2, row=1, col=0)

34

In [111]:
entry_sum(matrix_1, matrix_2, row=1, col=1)

382

In [106]:
entry_sum(matrix_1, matrix_2, row=2, col=0)

186

In [107]:
entry_sum(matrix_1, matrix_2, row=2, col=1)

2816

### Next Try
The `entry_sum()` function did exactly what it was supposed to. This is a mixed blessing, because while this means a key part of our code works as intended, it also means we have to look elsewhere to see where the error occurred.

In [126]:
def matrix_multiply(a, b):
    def entry_sum(row, col):
        # Calculate the value of an individual entry in the resultant matrix,
        # given the row and column indices of the entry
        this_sum = 0

        i = 0
        for num in a[row]:
            this_sum += num * b[i][col]
            i += 1

        return this_sum
        
    # For every row in the original matrix, add a row to the new matrix
    result = [list() for row in a]
    
    # Populate matrix with results
    r = 0
    for row in result:
        # Populate columns
        c = 0
        
        for col in range(1, min(len(a[1]), len(b[1])) + 1):  # Correction
            row.append(entry_sum(r, c))
            c += 1
            
        r += 1
    
    return(result)
        
matrix_multiply(matrix_1, matrix_2)

[[78, 295], [34, 382], [186, 2816]]

In [118]:
len(matrix_1[1])

3

In [119]:
len(matrix_2[1])

2

In [125]:
list(range(1, min(len(matrix_1[1]), len(matrix_2[1]) + 1)))

[1, 2]

In [127]:
np.matrix([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]]) * np.matrix([[10], [2], [2]])

matrix([[ 20],
        [ 62],
        [104]])

## Conclusion
While computer programs are rigid and logical, debugging them is more like an art. When a program goes wrong, pinpointing the error is not always an obvious task. Succesfully debugging a program involves:
* Knowing (on paper) what a correctly functioning program looks like. This includes knowing:
 * The result
 * The intermediate steps
* Knowing how the different pieces of your program are supposed to fit together
* Patience

There is no magic involved in debugging.